var Process1 = document.querySelector(".const-Process1")
var PRimg1= document.querySelector(".constPR-img1")
var fill = document.querySelector(".fill")
     Process1.addEventListener('mouseover', () =>{
        PRimg1.setAttribute('style', 'background-color: 007a5f;')
        fill.setAttribute('style', 'fill: #ffffff')
    })
    Process1.addEventListener('mouseout',() =>{
        PRimg1.setAttribute('style', 'background-color: #edf7f4; ')
        fill.setAttribute('style', 'fill: #007a5f')
    })    
var jurispru1 = document.querySelector(".jurispru-1")
var jurispruImg1 = document.querySelector(".jurispru-img1")
var fill1 = document.querySelector(".fillJ")
    jurispru1.addEventListener('mouseover', () =>{
        jurispruImg1.setAttribute('style', 'background-color: 007a5f;')
        fill1.setAttribute('style', 'fill: #ffffff')
    })
    jurispru1.addEventListener('mouseout',() =>{
        jurispruImg1.setAttribute('style', 'background-color: #edf7f4; ')
        fill1.setAttribute('style', 'fill: #007a5f')
    })
var doutri1 = document.querySelector(".doutri-1")
var doutriImg1 = document.querySelector(".doutri-img1")
var fill2 = document.querySelector(".fill2")
    doutri1.addEventListener('mouseover', () =>{
        doutriImg1.setAttribute('style', 'background-color: 007a5f;')
        fill2.setAttribute('style', 'fill: #ffffff')
    })
    doutri1.addEventListener('mouseout',() =>{
        doutriImg1.setAttribute('style', 'background-color: #edf7f4; ')
        fill2.setAttribute('style', 'fill: #007a5f')
    })   
var pecas1 = document.querySelector(".pecas-1")
var pecasImg1 = document.querySelector(".pecas-img1")
var fill3 = document.querySelector(".fill3")
    pecas1.addEventListener('mouseover', () =>{
        pecasImg1.setAttribute('style', 'background-color: 007a5f;')
        fill3.setAttribute('style', 'fill: #ffffff')
    })
    pecas1.addEventListener('mouseout',() =>{
        pecasImg1.setAttribute('style', 'background-color: #edf7f4; ')
        fill3.setAttribute('style', 'fill: #007a5f')
    })    
var legisl1 = document.querySelector(".legisl-1")
var legislImg1 = document.querySelector(".legisl-img1")
var fill4 = document.querySelector(".fill4")
    legisl1.addEventListener('mouseover', () =>{
        legislImg1.setAttribute('style', 'background-color: 007a5f;')
        fill4.setAttribute('style', 'fill: #ffffff')
    })
    legisl1.addEventListener('mouseout',() =>{
        legislImg1.setAttribute('style', 'background-color: #edf7f4; ')
        fill4.setAttribute('style', 'fill: #007a5f')
    })  
var model1 = document.querySelector(".model-1")
var modelImg1 = document.querySelector(".model-img1")
var fill5 = document.querySelector(".fill5")
    model1.addEventListener('mouseover', () =>{
        modelImg1.setAttribute('style', 'background-color: 007a5f;')
        fill5.setAttribute('style', 'fill: #ffffff')
    })
    model1.addEventListener('mouseout',() =>{
        modelImg1.setAttribute('style', 'background-color: #edf7f4; ')
        fill5.setAttribute('style', 'fill: #007a5f')
    })    
var advog1 = document.querySelector(".advog-1")
var advogImg1 = document.querySelector(".advog-img1")
var fill6 = document.querySelector(".fill6")
    advog1.addEventListener('mouseover', () =>{
        advogImg1.setAttribute('style', 'background-color: 007a5f;')
        fill6.setAttribute('style', 'fill: #ffffff')
    })
    advog1.addEventListener('mouseout',() =>{
        advogImg1.setAttribute('style', 'background-color: #edf7f4; ')
        fill6.setAttribute('style', 'fill: #007a5f')
    })   
var diaOf1 = document.querySelector(".diaOf-1")
var diaOfImg1 = document.querySelector(".diaOf-img1")
var fill7 = document.querySelector(".fill7")
    diaOf1.addEventListener('mouseover', () =>{
        diaOfImg1.setAttribute('style', 'background-color: 007a5f;')
        fill7.setAttribute('style', 'fill: #ffffff')
    })
    diaOf1.addEventListener('mouseout',() =>{
        diaOfImg1.setAttribute('style', 'background-color: #edf7f4; ')
        fill7.setAttribute('style', 'fill: #007a5f')
    })  
var msgCha = document.querySelector(".msg-Cha")
var ballCha = document.querySelector(".fillBall")
var chatAD = document.querySelector(".chatAD")
    chatAD.addEventListener("mouseover", ()=>{
        msgCha.setAttribute('style','color: #007a5f')
        ballCha.setAttribute('style','fill: #007a5f')
    })
    chatAD.addEventListener("mouseout", ()=>{
        msgCha.setAttribute('style','color: black')
        ballCha.setAttribute('style','fill: black')
    })